GET https://ca-backend-todo-dev.whitesmoke-f94160ee.westeurope.azurecontainerapps.io

###

POST https://ca-backend-todo-dev.whitesmoke-f94160ee.westeurope.azurecontainerapps.io/todos/

{
  "title": "30septembrie"
}

###

GET https://ca-backend-todo-dev.whitesmoke-f94160ee.westeurope.azurecontainerapps.io/todos
