#cloud-config
groups:
- sudo: [root, sys, adminuser]
- cloud-users
users:
- default
- name: runneruser
  primary_group: cloud-users
  sudo: "ALL=(ALL) NOPASSWD:ALL"
packages:
  - python
  - npm
  - nvm
  - pip
  - zip
  - unzip
  - curl
  - tar
  - jq
  - az
  - docker.io
  - docker-buildx

write_files:
- path: /home/adminuser/scripts/runner-start-backend.sh
  permissions: "0777"
  content: |
    #!/bin/bash
    az login --identity --client-id 244f3187-60e9-4a5a-917e-ed8968dd620e
    PAT=$(az keyvault secret show --name PAT-Runner-dev --vault-name kv-todo-dev-123 --query value -o tsv)
    REPO="CorporalCiprian/backend-todo"

    RUNNER_NAME=backend-runner-$HOSTNAME
    RUNNER_TOKEN=$(curl -sX POST -H "Authorization: token $PAT" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/$REPO/actions/runners/registration-token" | jq -r .token)
    mkdir /home/adminuser/actions-runner-backend 
    cd /home/adminuser/actions-runner-backend 
    curl -o actions-runner-linux-x64-2.336.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.336.0/actions-runner-linux-x64-2.336.0.tar.gz 
    tar xzf ./actions-runner-linux-x64-2.336.0.tar.gz 
    ./config.sh --url https://github.com/CorporalCiprian/backend-todo --token $RUNNER_TOKEN --name $RUNNER_NAME --unattended --replace 
    sudo ./svc.sh install && sudo ./svc.sh start

- path: /home/adminuser/scripts/runner-start-frontend.sh
  permissions: "0777"
  content: |
    #!/bin/bash
    az login --identity --client-id 244f3187-60e9-4a5a-917e-ed8968dd620e
    PAT=$(az keyvault secret show --name PAT-Runner-dev --vault-name kv-todo-dev-123 --query value -o tsv)
    REPO="CorporalCiprian/frontend-todo"

    RUNNER_NAME=frontend-runner-$HOSTNAME
    RUNNER_TOKEN=$(curl -sX POST -H "Authorization: token $PAT" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/$REPO/actions/runners/registration-token" | jq -r .token)
    mkdir /home/adminuser/actions-runner-frontend 
    cd /home/adminuser/actions-runner-frontend 
    curl -o actions-runner-linux-x64-2.336.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.336.0/actions-runner-linux-x64-2.336.0.tar.gz 
    tar xzf ./actions-runner-linux-x64-2.336.0.tar.gz 
    ./config.sh --url https://github.com/CorporalCiprian/frontend-todo --token $RUNNER_TOKEN --name $RUNNER_NAME --unattended --replace
    sudo ./svc.sh install && sudo ./svc.sh start
runcmd:
- sudo apt update && sudo apt upgrade -y
- sudo apt install python3 python3-pip python3-venv python3-dev -y  
- chown -R adminuser /home/adminuser
- sudo usermod -aG docker adminuser
- curl -fsSL 'https://azurecliprod.blob.core.windows.net/$root/deb_install.sh' | sudo bash
- sudo -u adminuser /home/adminuser/scripts/runner-start-backend.sh

- sudo -u adminuser /home/adminuser/scripts/runner-start-frontend.sh

- |
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.6/install.sh | bash
  \. "$HOME/.nvm/nvm.sh"
  nvm install 24
  
- |
  curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs 2>/dev/null)-prod $(lsb_release -cs 2>/dev/null) main" > /etc/apt/sources.list.d/dotnetdev.list'
  sudo apt-get update
  sudo apt-get install azure-functions-core-tools-4